### PR TITLE
Enable logging through syslog

### PR DESCRIPTION
**Pull request by bbolli**
This might be a desirable feature for some people.

### CODE REVIEW

**Comment by skeeto** [comment]
Thanks! I'm mostly satisfied with these changes, but I have questions 
and comments.

As you noticed, vsyslog(3) is non-standard, though it *is* implemented 
on every system I tested. However, as with most non-standard interfaces, 
it has feature test macro issues. On Linux it requires _DEFAULT_SOURCE 
in order to be visible, but that only works on Linux. On FreeBSD the 
function is still hidden, and there are no feature test macro to bring 
it out other than using *no* feature test macros whatsoever.

Further, using _DEFAULT_SOURCE masks other portability issues that I 
would prefer to be obvious and immediate. I'd rather go without this 
feature than use _DEFAULT_SOURCE. Fortunately syslog(3) is available 
starting in POSIX.1-2001, so perhaps there's a clean enough way to use 
that instead (variadic macro?)?

Are the LOG_* definitions guaranteed to be in any particular ascending 
descending order, and consecutive? I'm not seeing anything about that 
here:

https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/syslog.h.html

Rather than attempt to parse argv[0], I'd prefer to just #define a 
consistent program name string. This can be used in stdout log messages 
as well.

Is the -s switch something you came up with yourself, or is this a 
conventional switch to logging to the syslog? If there is a convention 
I'd like to follow it. I see that nfsd and inotifywait use -s exactly 
this way, and slapd uses -s with an argument. I'm also seeing --syslog 
and --syslog-method= in other programs, though I don't intend to switch 
to long options in Endlessh. It seems -s is the correct and obvious 
choice.

Please don't increment the version number. I'll do that when I'm ready 
to make a release.

**Comment by bbolli** [comment]
> As you noticed, vsyslog(3) is non-standard

Would you be OK with a variant that `snprintf`s into a buffer and then uses `syslog(3)` to output?

> Are the LOG_* definitions guaranteed to be in any particular ascending
descending order, and consecutive?

Going by the standard, I'd think they don't have to be. In practice though... I'll try to come up with a better mapping.

> Please don't increment the version number.
OK.

**Comment by skeeto** [comment]
snprint() sounds perfectly reasonable. Good thinking! Remove vsyslog(), 
fix the LOG_* mapping, and I'm happy to accept this. Also, preferably, 
update your PR in-place (force push, rebase -i, etc.) so that I have 
nice, clean commits that I can ff on master. Thanks!

**Comment by bbolli** [comment]
@skeeto I had already force-pushed a new version when you replied. Please re-review :-)

**Comment by skeeto** [comment]
This all looks great except for one thing: The buffer should not be 
passed to syslog(3) as the format string. Yes, I could fix this myself 
after merging, but I want nice clean commits, I want GitHub to recognize 
the merge, and you know what you're doing. :-) Here's the patch to squash 
into 4712061:


diff --git a/endlessh.c b/endlessh.c
index 6312ecb..f59e20e 100644
--- a/endlessh.c
+++ b/endlessh.c
@@ -99,7 +99,7 @@ logsyslog(enum loglevel level, const char *format, ...)
         char buf[256];
         vsnprintf(buf, sizeof buf, format, ap);
         va_end(ap);
-        syslog(prio_map[level], buf);
+        syslog(prio_map[level], "%s", buf);
 
         errno = save;
     }

**Comment by bbolli** [comment]
I'm sorry about that, you're right. I'll update this commit.

**Comment by skeeto** [comment]
Thanks so much! This was a productive, tidy, and effective PR.

**Pull request merged**
